### ISSUE TITLE
SumoUpload does not work on worker nodes, only built-in node

### ISSUE THREAD

**Issue by fdaca** [jenkinsci/sumologic-publisher-plugin#39]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins: 2.424
OS: Linux - 4.14.268-205.500.amzn2.x86_64
Java: 11.0.20.1 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
Parameterized-Remote-Trigger:3.2.0
amazon-ecr:1.114.vfd22430621f5
amazon-ecs:1.48
analysis-model-api:11.8.0
ansicolor:1.0.4
ant:497.v94e7d9fffa_b_9
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
artifact-manager-s3:822.vf129d4836c31
artifactory:3.18.9
audit-trail:347.v1fc515cc462b_
authentication-tokens:1.53.v1c90fd9191a_b_
authorize-project:1.7.1
aws-codebuild:0.59
aws-credentials:218.v1b_e9466ec5da_
aws-global-configuration:128.ve2c5685a_09c3
aws-java-sdk:1.12.529-406.vdeff15e5817d
aws-java-sdk-cloudformation:1.12.529-406.vdeff15e5817d
aws-java-sdk-codebuild:1.12.529-406.vdeff15e5817d
aws-java-sdk-ec2:1.12.529-406.vdeff15e5817d
aws-java-sdk-ecr:1.12.529-406.vdeff15e5817d
aws-java-sdk-ecs:1.12.529-406.vdeff15e5817d
aws-java-sdk-efs:1.12.529-406.vdeff15e5817d
aws-java-sdk-elasticbeanstalk:1.12.529-406.vdeff15e5817d
aws-java-sdk-iam:1.12.529-406.vdeff15e5817d
aws-java-sdk-kinesis:1.12.529-406.vdeff15e5817d
aws-java-sdk-logs:1.12.529-406.vdeff15e5817d
aws-java-sdk-minimal:1.12.529-406.vdeff15e5817d
aws-java-sdk-secretsmanager:1.12.529-406.vdeff15e5817d
aws-java-sdk-sns:1.12.529-406.vdeff15e5817d
aws-java-sdk-sqs:1.12.529-406.vdeff15e5817d
aws-java-sdk-ssm:1.12.529-406.vdeff15e5817d
aws-parameter-store:1.2.2
basic-branch-build-strategies:81.v05e333931c7d
blueocean:1.27.7
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.27.7
blueocean-commons:1.27.7
blueocean-config:1.27.7
blueocean-core-js:1.27.7
blueocean-dashboard:1.27.7
blueocean-display-url:2.4.2
blueocean-events:1.27.7
blueocean-git-pipeline:1.27.7
blueocean-github-pipeline:1.27.7
blueocean-i18n:1.27.7
blueocean-jira:1.27.7
blueocean-jwt:1.27.7
blueocean-personalization:1.27.7
blueocean-pipeline-api-impl:1.27.7
blueocean-pipeline-editor:1.27.7
blueocean-pipeline-scm-api:1.27.7
blueocean-rest:1.27.7
blueocean-rest-impl:1.27.7
blueocean-web:1.27.7
bootstrap5-api:5.3.2-1
bouncycastle-api:2.29
branch-api:2.1128.v717130d4f816
build-discarder:139.v05696a_7fe240
build-failure-analyzer:2.4.2
build-timeout:1.31
build-token-root:151.va_e52fe3215fc
build-user-vars-plugin:1.9
build-with-parameters:76.v9382db_f78962
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.0.2
cloudbees-bitbucket-branch-source:845.v27a_d5823911b_
cloudbees-folder:6.848.ve3b_fd7839a_81
code-coverage-api:4.7.0
command-launcher:107.v773860566e2e
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.10.0-78.v3e7b_ea_d5a_fe1
compact-columns:1.185.vf3851b_4d31fe
config-file-provider:959.vcff671a_4518b_
configuration-as-code:1714.v09593e830cfa
configuration-as-code-secret-ssm:1.0.2-SUMO
copyartifact:722.v0662a_9b_e22a_c
credentials:1271.v54b_1c2c6388a_
credentials-binding:636.v55f1275c7b_27
data-tables-api:1.13.6-4
disable-github-multibranch-status:1.2
display-url-api:2.3.9
docker-commons:439.va_3cb_0a_6a_fb_29
docker-workflow:572.v950f58993843
durable-task:523.va_a_22cf15d5e0
ec2:1628.v6d7b_fc58b_a_1d
ec2-fleet:3.0.1
echarts-api:5.4.0-6
email-ext:2.101
external-monitor-job:215.v2e88e894db_f8
favorite:2.4.3
font-awesome-api:6.4.2-1
forensics-api:2.3.0
generic-webhook-trigger:1.87.0
git:5.2.0
git-client:4.5.0
git-forensics:2.0.0
git-server:99.va_0826a_b_cdfa_d
github:1.37.3
github-api:1.314-431.v78d72a_3fe4c3
github-branch-source:1741.va_3028eb_9fd21
github-checks:554.vb_ee03a_000f65
github-pr-comment-build:96.v9ff13b69dd66
gradle:2.8.2
groovy:453.vcdb_a_c5c99890
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
hidden-parameter:138.v2a_c30d04e566
htmlpublisher:1.32
http_request:1.18
inline-pipeline:1.0.3
instance-identity:173.va_37c494ec4e5
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.15.2-350.v0c2f3f8fc595
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javadoc:243.vb_b_503b_b_45537
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.8-1
jdk-tool:73.vddf737284550
jenkins-design-language:1.27.7
jersey2-api:2.40-1
jira:3.11
jjwt-api:0.11.5-77.v646c772fddb_0
jmh-report:0.9.0
jnr-posix-api:3.1.18-1
job-dsl:1.85
jobConfigHistory:1229.v3039470161a_d
jquery3-api:3.7.1-1
jsch:0.2.8-65.v052c39de79b_2
jsonschema:0.1.0-SNAPSHOT (private-2021-02-26T09:47:56Z-wbederski)
junit:1240.vf9529b_881428
ldap:701.vf8619de9160a_
lockable-resources:1172.v4b_8fc8eed570
mailer:463.vedf8358e006b_
mapdb-api:1.0.9-28.vf251ce40855d
matrix-auth:3.2.1
matrix-project:808.v5a_b_5f56d6966
maven-plugin:3.23
metrics:4.2.18-442.v02e107157925
mina-sshd-api-common:2.10.0-69.v28e3e36d18eb_
mina-sshd-api-core:2.10.0-69.v28e3e36d18eb_
monitoring:1.95.0
multibranch-build-strategy-extension:1.0.10
next-executions:207.va_888556123ec
node-iterator-api:49.v58a_8b_35f8363
okhttp-api:4.11.0-157.v6852a_a_fa_ec11
pam-auth:1.10
parameterized-scheduler:255.v73827fcdf618
pipeline-aws:1.43
pipeline-build-step:505.v5f0844d8d126
pipeline-github:2.8-155.8eab375ac9f8
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:689.veec561a_dee13
pipeline-input-step:477.v339683a_8d55e
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2144.v077a_d1928a_40
pipeline-model-definition:2.2144.v077a_d1928a_40
pipeline-model-extensions:2.2144.v077a_d1928a_40
pipeline-rest-api:2.33
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2144.v077a_d1928a_40
pipeline-stage-view:2.33
pipeline-utility-steps:2.16.0
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:3.3.0
prism-api:1.29.0-8
pubsub-light:1.17
resource-disposer:0.23
reverse-proxy-auth-plugin:1.7.7
role-strategy:689.v731678c3e0eb_
run-condition:1.5
saml:4.429.v9a_781a_61f1da_
scm-api:676.v886669a_199a_a_
scoverage:1.4.0
script-security:1275.v23895f409fb_d
scriptler:321.v74a_851a_e7ed6
show-build-parameters:1.0
simple-theme-plugin:172.v4b_8766c70078
slack:684.v833089650554
snakeyaml-api:2.2-111.vc6598e30cc65
snyk-security-scanner:4.0.2
sse-gateway:1.26
ssh-agent:333.v878b_53c89511
ssh-credentials:308.ve4497b_ccd8f4
ssh-slaves:2.916.vd17b_43357ce4
sshd:3.312.v1c601b_c83b_0e
structs:325.vcb_307d2a_2782
subversion:2.17.3
sumologic-publisher:2.2.4
support-core:1356.vd0f980edfa_46
throttle-concurrents:2.14
timestamper:1.26
token-macro:384.vf35b_f26814ec
trilead-api:2.84.v72119de229b_7
uno-choice:2.7.2
variant:60.v7290fc0eb_b_cd
view-job-filters:369.ve0513a_a_f5524
warnings-ng:10.4.0
workflow-aggregator:596.v8c21c963d92d
workflow-api:1281.vca_5fddb_3fceb_
workflow-basic-steps:1042.ve7b_140c4a_e0c
workflow-cps:3791.va_c0338ea_b_59c
workflow-durable-task-step:1289.v4d3e7b_01546b_
workflow-job:1346.v180a_63f40267
workflow-multibranch:756.v891d88f2cd46
workflow-scm-step:415.v434365564324
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:865.v43e78cc44e0d
ws-cleanup:0.45
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Amazon Linux

### Reproduction steps

Run pipeline:
```
pipeline {
    agent none
    stages {
        stage ('test') {
            steps {
                script {
                    node('other') {
                          sh "mkdir target"
                          sh "echo hello > target/hello.txt"
                          SumoUpload(includePathPattern: '*.txt', workingDir: 'target/')
                    }
                }
            }
        }
    }
}
```

### Expected Results

Successful run

### Actual Results

Exception in piepline:

```
java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.
	at jenkins.model.Jenkins.get(Jenkins.java:819)
	at com.sumologic.jenkins.jenkinssumologicplugin.PluginDescriptorImpl.getInstance(PluginDescriptorImpl.java:99)
	at com.sumologic.jenkins.jenkinssumologicplugin.sender.LogSender.<init>(LogSender.java:72)
	at com.sumologic.jenkins.jenkinssumologicplugin.sender.LogSender$LogSenderHolder.<clinit>(LogSender.java:122)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to EC2 (ci-jenkins-executor) - e2e-ui tests runner (i-0074bba769c6064f5)
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1787)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1003)
		at hudson.FilePath.act(FilePath.java:1192)
		at hudson.FilePath.act(FilePath.java:1181)
		at com.sumologic.jenkins.jenkinssumologicplugin.sender.SumoLogicFileUploadStep$Execution.run(SumoLogicFileUploadStep.java:221)
		at com.sumologic.jenkins.jenkinssumologicplugin.sender.SumoLogicFileUploadStep$Execution.run(SumoLogicFileUploadStep.java:128)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:829)
Caused: java.lang.ExceptionInInitializerError
	at com.sumologic.jenkins.jenkinssumologicplugin.sender.LogSender.getInstance(LogSender.java:126)
	at com.sumologic.jenkins.jenkinssumologicplugin.sender.LogSenderHelper.sendFilesData(LogSenderHelper.java:71)
	at com.sumologic.jenkins.jenkinssumologicplugin.sender.SumoLogicFileUploadStep$FileListUploader.sendFilesData(SumoLogicFileUploadStep.java:300)
	at com.sumologic.jenkins.jenkinssumologicplugin.sender.SumoLogicFileUploadStep$FileListUploader.invoke(SumoLogicFileUploadStep.java:287)
	at com.sumologic.jenkins.jenkinssumologicplugin.sender.SumoLogicFileUploadStep$FileListUploader.invoke(SumoLogicFileUploadStep.java:269)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3578)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:377)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: b822e029-de42-4548-9520-8a330c2a2384
Caused: java.io.IOException: Remote call on EC2 (ci-jenkins-executor) - e2e-ui tests runner (i-0074bba769c6064f5) failed
	at hudson.remoting.Channel.call(Channel.java:1007)
	at hudson.FilePath.act(FilePath.java:1192)
	at hudson.FilePath.act(FilePath.java:1181)
	at com.sumologic.jenkins.jenkinssumologicplugin.sender.SumoLogicFileUploadStep$Execution.run(SumoLogicFileUploadStep.java:221)
	at com.sumologic.jenkins.jenkinssumologicplugin.sender.SumoLogicFileUploadStep$Execution.run(SumoLogicFileUploadStep.java:128)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sumoanema** [comment]
@fdaca - Have released the latest version of the plugin with the fix - https://github.com/jenkinsci/sumologic-publisher-plugin/releases/tag/sumologic-publisher-2.2.5
